# This file configures the gtfs-validator app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtfs-validator-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gtfs-validator
  template:
    metadata:
      labels: latest
        app: gtfs-validator
    spec:
      containers:
        - name: gtfs-validator
          image: us-east1-docker.pkg.dev/gtfs-validator-320318/gtfs-validator-repo/gtfs-validator-gke:latest
          # This app listens on port 8080 for web traffic by default.
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
