name: Integration tests

on:
  push:
    branches: [ master, new-test-module ]

jobs:
  test-comparator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare version name
        id: prep
        run: |
          VERSION_TAG=edge
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION_TAG=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION_TAG=-$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION_TAG=-pr-${{ github.event.number }}
          fi
          if [ ${VERSION_TAG} != ${GITHUB_REF#refs/tags/} ]; then
            VERSION_TAG=v${VERSION_TAG}-sha-${GITHUB_SHA::8}-SNAPSHOT
          fi
          echo ::set-output name=versionTag::${VERSION_TAG}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Run Java tests
        uses: eskatos/gradle-command-action@v1
        env:
          versionTag: ${{ steps.prep.outputs.versionTag }}
        with:
          arguments: testReport
      - name: Persist **Passing** Java tests merged report
        uses: actions/upload-artifact@v2
        with:
          name: Test report - Java -- ${{ steps.prep.outputs.versionTag }}
          path: build/reports/allTests/
      - name: Persist **Failing** Java tests unmerged reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: Test report - Java -- ${{ steps.prep.outputs.versionTag }}
          path: |
            comparator/build/reports/tests/
  pack-comparator:
    needs: [test-comparator]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare version name
        id: prep
        run: |
          VERSION_TAG=edge
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION_TAG=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION_TAG=-$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION_TAG=-pr-${{ github.event.number }}
          fi
          if [ ${VERSION_TAG} != ${GITHUB_REF#refs/tags/} ]; then
            VERSION_TAG=v${VERSION_TAG}-sha-${GITHUB_SHA::8}-SNAPSHOT
          fi
          echo ::set-output name=versionTag::${VERSION_TAG}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Package cli app jar with Gradle
        uses: eskatos/gradle-command-action@v1
        env:
          versionTag: ${{ steps.prep.outputs.versionTag }}
        with:
          arguments: shadowJar
      - name: Persist cli app jar
        uses: actions/upload-artifact@v2
        with:
          name: output-comparator-cli-jar -- ${{ steps.prep.outputs.versionTag }}
          path: comparator/build/libs/comparator.jar
  download-latest-gtfs-validator-release-jar:
    needs: [ pack-comparator ]
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Download last release of the validator
        uses: suisei-cn/actions-download-file@v1
        id: gtfs-validator
        with:
          url: "https://github.com/MobilityData/gtfs-validator/releases/download/v2.0.0/gtfs-validator-v2.0.0_cli.jar"
          target: public/
      - name: Persist reference jar
        uses: actions/upload-artifact@v2
        with:
          name: reference_jar
          path: public/gtfs-validator*.jar
  fetch-urls:
    needs: [ pack-comparator ]
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Get url list as json
        id: set-matrix
        # The below outputs a JSON array and uses GitHub Actions magic (::set-output) to set
        # an output variable
        run: |
          DATASETS=$(curl https://gtfs-validator.free.beeceptor.com/datasets)
          echo $DATASETS
          echo "::set-output name=matrix::$DATASETS"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  pack-latest-changes:
    needs: [ pack-comparator ]
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v1
      - name: Prepare version name
        id: prep
        run: |
          VERSION_TAG=edge
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION_TAG=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION_TAG=-$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION_TAG=-pr-${{ github.event.number }}
          fi
          if [ ${VERSION_TAG} != ${GITHUB_REF#refs/tags/} ]; then
            VERSION_TAG=v${VERSION_TAG}-sha-${GITHUB_SHA::8}-SNAPSHOT
          fi
          echo ::set-output name=versionTag::${VERSION_TAG}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Package cli app jar with Gradle
        uses: eskatos/gradle-command-action@v1
        env:
          versionTag: ${{ steps.prep.outputs.versionTag }}
        with:
          arguments: shadowJar
      - name: Persist cli app jar
        uses: actions/upload-artifact@v2
        with:
          name: latest_changes_cli
          path: main/build/libs/gtfs-validator-${{ steps.prep.outputs.versionTag }}_cli.jar
  get-latest-changes-report:
    needs: [ pack-latest-changes, fetch-urls ]
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix: ${{ fromJson(needs.fetch-urls.outputs.matrix) }}
    steps:
      - name: Download latest changes .jar file from previous job
        uses: actions/download-artifact@v2
        with:
          name: latest_changes_cli
      - name: Execute jar
        run: java -jar gtfs-validator*.jar -u ${{ matrix.url }} -o output/${{ matrix.output }} -v latest_changes.json
      - name: Persist reports
        uses: actions/upload-artifact@v2
        with:
          name: reports_all
          path: output
  get-reference-report:
    needs: [ download-latest-gtfs-validator-release-jar, fetch-urls ]
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix: ${{ fromJson(needs.fetch-urls.outputs.matrix) }}
    steps:
      - name: Download latest changes .jar file from previous job
        uses: actions/download-artifact@v2
        with:
          name: reference_jar
      - name: Execute jar
        # the following line will be changed after v3.0 is published without -f CLI parameter
        run: java -jar gtfs-validator*.jar -u ${{ matrix.url }} -o output/${{ matrix.output }} -f ca-test
      - name: Persist reports
        uses: actions/upload-artifact@v2
        with:
          name: reports_all
          path: output
  compare-outputs:
    needs: [get-reference-report, get-latest-changes-report, fetch-urls, pack-comparator]
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix: ${{ fromJson(needs.fetch-urls.outputs.matrix) }}
    steps:
      - name: Download all validation reports
        uses: actions/download-artifact@v2
        with:
          name: reports_all
      - name: Explore folder # to be replaced by the execution of a comparator jar
        run: |
              echo ${{ matrix.output }}
              ls ${{ matrix.output }} -a
