name: Integration tests

on:
  push:
    branches: [ master, new-test-module ] #<-- replace extend-end-to-end by the name of the agency/publisher

jobs:
  download-latest-gtfs-validator-release-jar:
    runs-on: ubuntu-latest
    steps:
      - uses: suisei-cn/actions-download-file@v1
      - name: Download last release of the validator
        id: gtfs-validator
        with:
          url: "https://github.com/MobilityData/gtfs-validator/releases/download/v2.0.0/gtfs-validator-v2.0.0_cli.jar"
          target: public/
