name: Integration tests

on:
  push:
    branches: [ master, new-test-module ] #<-- replace extend-end-to-end by the name of the agency/publisher

jobs:
  download-latest-gtfs-validator-release-jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download last release of the validator
        uses: suisei-cn/actions-download-file@v1
        id: gtfs-validator
        with:
          url: "https://github.com/MobilityData/gtfs-validator/releases/download/v2.0.0/gtfs-validator-v2.0.0_cli.jar"
          target: public/
  loop-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        env:
          URLS: '["url1", "url2", "url3"]'
      strategy:
        matrix:
          urls: ${{ env.URLS }}
      - run: |
        echo ${{ matrix.urls }}
#    strategy:
#      matrix:
#        urls: URLS
#      - name: Echo items in list (for loop using Github Action strategy)
#        run: |
#          echo ${{ matrix.urls }}
