name: Integration tests

on:
  push:
    branches: [ master, new-test-module ] #<-- replace extend-end-to-end by the name of the agency/publisher

jobs:
  download-latest-gtfs-validator-release-jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download last release of the validator
        uses: suisei-cn/actions-download-file@v1
        id: gtfs-validator
        with:
          url: "https://github.com/MobilityData/gtfs-validator/releases/download/v2.0.0/gtfs-validator-v2.0.0_cli.jar"
          target: public/
  loop-check:
    strategy:
      matrix:
        urls: ["url1", "url2", "url3"] #TODO: use env var here
    runs-on: ubuntu-latest
    steps:
      - name: Echo items in list (for loop using Github Action strategy)
        run: |
          echo ${{ matrix.urls }}
          #TODO: execute latest validator version and store the validation reports
          #TODO: calculate hash code for each dataset and compare to what is in the archive
          #TODO: if hashes are different execute v2.0 on the dataset and compare the two outputs
          #TODO: else, compare the two outputs (one from the archive, the other one from this action)
